name: 'Go Test'
description: 'Runs go test, vet/staticcheck and uploads coverage.'
inputs:
  coveralls_parallel:
    type: boolean
    default: false
  github_token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'
    - run: "go vet ./..."
      shell: bash
    - run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...    
      shell: bash
    - run: go test -v -race -covermode atomic -coverprofile=profile.cov ./...
      shell: bash
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        parallel: ${{ inputs.coveralls_parallel }}
      if: github.event_name != 'pull_request'
