name: go test
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - id: go-test
          uses: djherbis/actions/go-test@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}