name: go test
on:
  workflow_call:
    inputs:
      coveralls_parallel:
        type: boolean
        default: false
      runs-on:
        type: string
        default: ubuntu-latest
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - run: "go vet ./..."
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...    
      - run: go test -v -race -covermode atomic -coverprofile=covprofile ./...
      - name: Send coverage
        env:
          COVERALLS_PARALLEL: ${{ inputs.coveralls_parallel }}
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        if: github.event_name != 'pull_request'
