name: go test
on:
  workflow_call:
    inputs:
      coveralls_parallel:
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - id: go-test
          uses: djherbis/actions/go-test@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            coveralls_parallel: ${{ inputs.coveralls_parallel }}